# Base image: full Python image (better wheel compatibility)
FROM python:3.10.10

# Set working directory
WORKDIR /app

# Copy requirements first
COPY requirements.txt .


RUN pip install --no-cache-dir -r requirements.txt --prefer-binary

# Copy application code
COPY . .

# Expose port
EXPOSE 8000

# Run FastAPI with Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]